version: 2
updates:
- package-ecosystem: pip
  directory: "/src"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: protobuf
    versions:
    - 3.14.0
    - 3.15.0
    - 3.15.1
    - 3.15.2
    - 3.15.3
    - 3.15.4
    - 3.15.5
    - 3.15.6
    - 3.15.7
  - dependency-name: google-api-core
    versions:
    - 1.25.1
    - 1.26.0
    - 1.26.1
    - 1.26.2
  - dependency-name: sentry-sdk
    versions:
    - 0.19.5
    - 0.20.0
    - 0.20.1
    - 0.20.2
    - 0.20.3
  - dependency-name: pytest-mock
    versions:
    - 3.5.1
  - dependency-name: packaging
    versions:
    - "20.8"
